### ISSUE TITLE
I can't install it.

### ISSUE THREAD

**Issue by viccy5022** [dora2-iOS/ra1npoc#13]
this is the log. Dear what the problem?

`./builtin.sh
xcrun -sdk macosx gcc -I./include -Wall -Os -DBUILTIN_PAYLOAD -framework IOKit -framework CoreFoundation main.c io/iousb.c common/common.c soc/t8010_t8015.c soc/t7000_s8000.c soc/s5l8960x.c -o ra1npoc_macosx
xcrun -sdk iphoneos gcc -I./include -Wall -Os -DIPHONEOS_ARM -DBUILTIN_PAYLOAD -framework IOKit -framework CoreFoundation main.c io/iousb.c common/common.c soc/t8010_t8015.c soc/t7000_s8000.c soc/s5l8960x.c -arch armv7 -arch arm64 -o ra1npoc_iphoneos
xcrun: error: SDK "iphoneos" cannot be located
xcrun: error: SDK "iphoneos" cannot be located
In file included from main.c:26:
./include/io/iousb.h:4:10: fatal error: 'CoreFoundation/CoreFoundation.h' file not found
#include <CoreFoundation/CoreFoundation.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./include/io/iousb.h:4:10: note: did not find header 'CoreFoundation.h' in framework 'CoreFoundation' (loaded from '/System/Library/Frameworks')
1 error generated.
io/iousb.c:1:10: fatal error: 'CoreFoundation/CoreFoundation.h' file not found
#include <CoreFoundation/CoreFoundation.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
io/iousb.c:1:10: note: did not find header 'CoreFoundation.h' in framework 'CoreFoundation' (loaded from '/System/Library/Frameworks')
1 error generated.
In file included from common/common.c:26:
./include/io/iousb.h:4:10: fatal error: 'CoreFoundation/CoreFoundation.h' file not found
#include <CoreFoundation/CoreFoundation.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./include/io/iousb.h:4:10: note: did not find header 'CoreFoundation.h' in framework 'CoreFoundation' (loaded from '/System/Library/Frameworks')
1 error generated.
In file included from soc/t8010_t8015.c:26:
./include/io/iousb.h:4:10: fatal error: 'CoreFoundation/CoreFoundation.h' file not found
#include <CoreFoundation/CoreFoundation.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./include/io/iousb.h:4:10: note: did not find header 'CoreFoundation.h' in framework 'CoreFoundation' (loaded from '/System/Library/Frameworks')
1 error generated.
In file included from soc/t7000_s8000.c:26:
./include/io/iousb.h:4:10: fatal error: 'CoreFoundation/CoreFoundation.h' file not found
#include <CoreFoundation/CoreFoundation.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./include/io/iousb.h:4:10: note: did not find header 'CoreFoundation.h' in framework 'CoreFoundation' (loaded from '/System/Library/Frameworks')
1 error generated.
In file included from soc/s5l8960x.c:26:
./include/io/iousb.h:4:10: fatal error: 'CoreFoundation/CoreFoundation.h' file not found
#include <CoreFoundation/CoreFoundation.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./include/io/iousb.h:4:10: note: did not find header 'CoreFoundation.h' in framework 'CoreFoundation' (loaded from '/System/Library/Frameworks')
1 error generated.
make: *** [builtin] Error 1

**Comment by viccy5022** [comment]
> 安装 xcode，如果不起作用，请使用 xcode-select 设置路径。

Thanks dear. I will try. By the way , did it support big sur 11.6?

**Comment by dora2-iOS** [comment]
I haven't always tested for a particular version, but there shouldn't be anything that limits the build environment.

**Comment by viccy5022** [comment]
> 我并不总是针对特定版本进行测试，但不应该有任何限制构建环境的东西。

OK thanks so much
