### ISSUE TITLE
Stuck at : [io_get_serial] Found serial number!

### ISSUE THREAD

**Issue by 210Anyone** [dora2-iOS/ra1npoc#2]
Host Device : iPhone X (iPhone10,3 iOS 14.4.2) Jailbroke with checkra1n and odysseyra1n

Taget Device : iPad 6th Wifi (iPad7,5 Wifi iOS 14.6)

the message `[io_get_serial] Found serial number!` keep repeating and not continuing the process.

**Comment by dora2-iOS** [comment]
for iOS 14, bin must be placed in `/usr/local/bin`. Since it had already added that description, so close this.
